# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/point_cloud',
                'doc_host': 'https://valentina-lacivita.github.io',
                'git_url': 'https://github.com/valentina-lacivita/point_cloud',
                'lib_path': 'point_cloud'},
  'syms': {'point_cloud.core': {'point_cloud.core.foo': ('core.html#foo', 'point_cloud/core.py')}}}
